networks:
  dmz-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
  internal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

services:
  web01:
    build: ./WEB
    container_name: web01
    networks:
      dmz-net:
        ipv4_address: 172.18.0.3
      internal-net:
        ipv4_address: 172.19.0.5
    env_file: .env
    volumes:
      - ./WEB/app/certs:/app/certs:ro
    tty: true
    depends_on:
      db01:
        condition: service_healthy

  db01:
    image: postgres:15
    container_name: db01
    networks:
      internal-net:
        ipv4_address: 172.19.0.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}   
      POSTGRES_DB: ${DB_NAME}            
    volumes:
      - ./DB/init-users.sql:/docker-entrypoint-initdb.d/init-users.sql
      - ./postgres/tls:/var/lib/postgresql/tls
      - ./DB/postgres-entrypoint.sh:/usr/local/bin/postgres-entrypoint.sh:ro
    ports:
      - "5432:5432"
    tty: true
    entrypoint: /usr/local/bin/postgres-entrypoint.sh
    command: >
      postgres -c ssl=on
               -c ssl_cert_file=/var/lib/postgresql/tls-fixed/server.crt
               -c ssl_key_file=/var/lib/postgresql/tls-fixed/server.key
               -c ssl_ca_file=/var/lib/postgresql/tls-fixed/ca.crt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  nginx:
    image: nginx:latest
    container_name: nginx01
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/tls:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
    networks:
      dmz-net:
        ipv4_address: 172.18.0.4
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    depends_on:
      - web01
      

  ca01:
    image: debian:12
    container_name: ca01
    networks:
      internal-net:
        ipv4_address: 172.19.0.2
    tty: true
    working_dir: /pki
    volumes:
      - ./PKI:/pki
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y openssl ca-certificates curl &&
      tail -f /dev/null
      "

  fw01:
    build: ./FW
    container_name: fw01
    networks:
      dmz-net:
        ipv4_address: 172.18.0.2
      internal-net:
        ipv4_address: 172.19.0.4
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    tty: true
    volumes:
      - ./FW/nftables.conf:/etc/nftables.conf:ro
      - ./FW/rules.d:/etc/firewall/rules.d:ro
